require 'fileutils'

default_platform(:ios)

$ignore_file_path = '.xcovignore'

before_all do
	FileUtils.rm_rf("./UnitTestsReport")
	FileUtils.rm_rf("./CodeCoverageReport")
end

platform :ios do
	desc "Run tests and create a unit-test report"

	lane :unit_tests do
  		run_tests(
			scheme: "Basic-Car-Maintenance",
			only_testing: "Basic-Car-Maintenance-Tests",
			clean: true,
			code_coverage: true,
			device: "iPhone 15 Pro",
			skip_build: true,
			xcodebuild_formatter: 'xcbeautify -qq --is-ci --renderer github-actions',
			output_types: 'junit',
			output_directory: "./fastlane/UnitTestsReport"
		)

		xcov(
			scheme: "Basic-Car-Maintenance",
			only_project_targets: true,
			output_directory: "./fastlane/CodeCoverageReport"
  		)
	end

end
