name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main
      - dev
  
# Limit only the latest workflow created to run
concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Prepare xcconfig 
      run: cp Basic-Car-Maintenance.xcconfig.template Basic-Car-Maintenance.xcconfig
    
    - name: Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install packages
      run: xcodebuild -resolvePackageDependencies

    - name: Enable Build Tools
      run: cp fastlane/enable-build-tool-plugins.json ~/Library/org.swift.swiftpm/security/plugins.json
    
    - name: Install dependencies
      run: bundle install

    - name: Install build log formatter
      run: brew install xcbeautify
      
    - name: Run Unit Tests
      run: FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=60 bundle exec fastlane unit_tests
