name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
  
jobs:
  build:
    runs-on: macos-13
    

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Prepare xcconfig 
      run: cp Basic-Car-Maintenance.xcconfig.template Basic-Car-Maintenance.xcconfig
    
    - name: Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
      
    - name: Run Unit Tests
      run: bundle exec fastlane unit_tests
